git:
  pagers:
    - pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  colorArg: always
gui:
  theme:
    activeBorderColor:
      - '#fe8019' # Light Orange (Bright)
      - bold
    inactiveBorderColor:
      - '#a89984' # Light 4 / Fg4
    optionsTextColor:
      - '#83a598' # Light Blue
    selectedLineBgColor:
      - '#3c3836' # Dark 1 / Bg1 (Highlight background)
    selectedRangeBgColor:
      - '#504945' # Dark 2 / Bg2
    cherryPickedCommitBgColor:
      - '#8ec07c' # Light Aqua
    cherryPickedCommitFgColor:
      - '#d3869b' # Light Purple
    unstagedChangesColor:
      - '#fb4934' # Light Red
    defaultFgColor:
      - '#ebdbb2' # Light 1 / Fg1 (Main text color)
    searchingActiveBorderColor:
      - '#fabd2f' # Light Yellow
