#!/bin/zsh

(( $+commands[brew] )) || return 1

brew-ingrade \
  bat \
  btop \
  eza \
  fd \
  jq \
  lazygit \
  mise \
  ripgrep \
  starship \
  watch \
  wget \
  yazi \
  yq \
  zoxide \

install-fzf
